---
- name: started docker build  container
  hosts: db
  become: yes

  tasks:
  - name: Ensure docker  is present
    apt:
     name: docker.io
     state: present

  - name: Ensure python-pip is present
    apt:
     name: python-pip
     state: present

  - name: docker.py
    pip:
     name: docker.py

  - name:   docker build container boxfuse
    docker_container:
     name: buildboxfuse
     image: bitsl/buildboxfuse


  - name:   docker  container boxfuse started
    docker_container:
     name: bulildboxfuse
     image: bitsl/buildboxfuse
     state: started

- name: started docker Tomcat container
  hosts: web
  become: yes

  tasks:
  - name: Ensure docker  is present
    apt:
     name: docker.io
     state: present

  - name: Ensure python-pip is present
    apt:
     name: python-pip
     state: present

  - name: docker.py
    pip:
     name: docker.py

 # - name:   docker build container tomcate
 #   docker_container:
 #    name: tomcatboxfuse
 #    image: bitsl/tomcatboxfuse

  - name:   docker  container tomcate started
    docker_container:
     name: tomcatboxfuse
     image: bitsl/tomcatboxfuse
     state: started
     ports : "8080:8080"
