---
- name: started docker build  container
  hosts: db
  become: yes

  tasks:
  - name: Ensure docker  is present
    apt:
     name: docker.io
     state: present

  - name:  started docker build container
    shell: docker run -d -p 8080:8080 bitsl/buildboxfuse

- name: started docker Tomcat container
  hosts: web
  become: yes

  tasks:
  - name: Ensure docker  is present
    apt:
     name: docker.io
     state: present

  - name: started docker tomcat container
    shell: docker run -d -p 8080:8080 bitsl/tomcatboxfuse

#- name: install and started docker container buildboxfuse
#  hosts: db
#  become: yes

#  tasks:
#  - name: container buildboxfuse
#    docker_container:
#     name: bitsl
#     image: buildboxfuse

root@a1:~/test/hw88#

