---
- name: install Docker
  hosts: all
  become: yes

  tasks:
  - name: Ensure docker  is present
    apt:
     name: docker
     state: present


- name: install and started docker container buildboxfuse
  hosts: db
  become: yes

  tasks:
  - name: container buildboxfuse
    docker_container:
     name: bitsl
     image: buildboxfuse

